# Успех
TADA = [
    'CAACAgEAAxkBAAJvGGbE3gMujlNFVmXDbO8HKWpB_Ef_AALQAQACOA6CEcZSYwJr877tNQQ',
    'CAACAgIAAxkBAAJvG2bE3myttnYC_Vmy4p2YqDjK_qELAAKXDQACg5B5SorKwT47DT-5NQQ',
    'CAACAgIAAxkBAAJvHmbE3seGNkHd3LmCzkW-K9NvX6PzAAJZAAOtZbwU9LtHF4nhLQk1BA',
    'CAACAgIAAxkBAAJvIWbE3vgizYswRRX-vctk2FMediJDAAJKAgACVp29CslqxmhgGHrwNQQ',
    'CAACAgIAAxkBAAJvJGbE3w6RDa0xz7hDpDclnI9oK5j4AALFAAP3AsgPuzjRwaSVeKQ1BA',
    'CAACAgIAAxkBAAJvJ2bE3yfVYJYYD3HbwE_BZd3CifsGAAJKAAPANk8TL8ASxcW9exE1BA',
    'CAACAgIAAxkBAAJvKmbE4h1gquz_ZE3ro7Fd8QkDAfJJAALRAAP3AsgPsNUWIvohscw1BA',
    'CAACAgIAAxkBAAJvLWbE4nsv68SAbWslqWl8REVD4OttAALKDwACSyiRSc1Ng9DJ7M7cNQQ',
    'CAACAgIAAxkBAAJvMGbE4qm8n41yL-jIhYkPgNHSMYA6AAIjAAOtZbwUavIVntNd-N81BA'
]

# Приветствие
GREETING = [
    'CAACAgIAAxkBAAJwGmbGPmB9p_QBKto9m6ubTfxRvVozAAIxNAAC6BugStKvp8RmJqK8NQQ',
    'CAACAgIAAxkBAAJwHWbGPyn2hHOL75DsS4m9J0_JfVYwAAJhDQAC8Z1QS57gxAhC1JCvNQQ',
    'CAACAgIAAxkBAAJwIGbGPzKfPWSu-Qt1DIJseLwFd_a5AAIGUQACuFpgSX4QuFDtC4zaNQQ',
    'CAACAgIAAxkBAAJwI2bGPzpaVaFw-KizBHTYBW8bn0VYAAIJEQAC1PU5S3AxrumUnWFANQQ',
    'CAACAgIAAxkBAAJwJmbGP0LLHK7joDvoAAEirGuiOyLqqwACSDkAAg1pEEmEQqSwld9alTUE',
    'CAACAgIAAxkBAAJwKWbGP08rH4QTiAjLg4rhaWVBEEk5AAL4FgACy0bRSkm7Ldbys_ZcNQQ',
    'CAACAgIAAxkBAAJwLGbGP1u1lEgWParVaqr8Y3OylegqAAK4AAP3AsgPRguctOJOCzg1BA',
    'CAACAgIAAxkBAAJwL2bGP3Gw_DLd0_eN9WlnV4V2zWPiAAK6DwACAsSYSq3W9HdybYh3NQQ',
    'CAACAgIAAxkBAAJwMmbGP49R5E2UOJqZrpRe7jOpwBJ0AAIBAQACVp29CiK-nw64wuY0NQQ',
]
